funniture-Project/funniture-fe

funniture-fe/src/App.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/login/Singup.js
funniture-fe/src/pages/login/login.css
funniture-fe/src/pages/login/signup.css

#20 
- 로그인 페이지 및 회원가입 페이지 css 틀 잡기
- 메인 페이지에서 로그인 버튼 클릭 시 로그인 페이지 이동 / 회원가입 클릭 시 회원가입 페이지 이동

💄 [PR]2025/02/13 로그인 및 회원 가입 페이지 CSS 적용 -김규남💄

---

funniture-fe/src/layouts/adminlayout.css
funniture-fe/src/pages/admin/Rental.js
funniture-fe/src/pages/admin/rental.css

:lipstick:[PR]2025/02/13 관리자 예약정보 프론트엔드 레이아웃잡기-정은미:lipstick:

---

funniture-fe/src/App.js
funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/layouts/UserLayout.js
funniture-fe/src/layouts/userLayout.css
funniture-fe/src/pages/common/ListPage.js
funniture-fe/src/redux/modules/CategoryModuls.js

#32 
제공자 검색 조건 연결 및 제공자 선택 수정 + 초기화 버튼 수정 + css수정 등등
input 입력 데이터 useRef 관리로 변경

:art: [PR] 2025/2/15 제공자 검색 조건 연결 및 제공자 선택 수정-정예진 :art:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/admin/Rental.js
funniture-fe/src/pages/admin/rental.module.css

#36 
- 회사명으로 검색 할 때 회사 비동기처리해서 선택가능하게 함
- 아직...필터링 실패...ㅜ

:globe_with_meridians:[PR]2025/02/16 관리자 검색조건으로 예약조회 프론트&백 연결-정은미:globe_with_meridians:

---

funniture-fe/src/pages/admin/Rental.js
funniture-fe/src/pages/admin/rental.module.css

#43
- 초기화 아이콘 생성 -> 아이콘 눌렀을때 초기화 됨 (조건이 다 초기상태로 돌아옴!) => 전체조회 출력

:sparkles: [PR]2025/02/17 관리자 예약정보 검색조건 초기화-정은미:sparkles:

---

funniture-fe/src/pages/admin/Rental.js
funniture-fe/src/pages/admin/rental.module.css

#45 
-관리자 예약정보 검색 조건 선택 시 해당 조건에 맞는 예약건이 아무것도 없을 때 예외처리

:art:[PR]2025/02/17 관리자 예약정보 예외처리-정은미:art:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/admin/rental.module.css
funniture-fe/src/pages/login/Singup.js
funniture-fe/src/redux/modules/MemberModule.js

- #42
- 회원 가입 로직 : 포스트맨을 이용하여 back 검증 이후 front와 연결

✨[PR]2025/02/17 회원가입 (프론트 / 백 연결)  - 김규남✨

---

funniture-fe/src/apis/.env
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/login/Singup.js
funniture-fe/src/redux/modules/MemberModule.js

#42 
- 프론트-백엔드 로그인 연결
- 로그인 시 메인 페이지 이동
- 중복 체크 , 유효성 검증은 이후 예정

✨[PR]2025/02/17 프론트-백엔드 로그인 연결 - 김규남✨

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/login/Login.js

#42 
- 중복 회원가입 검증 / 로그인 검증
- 회원 가입 , 중복 회원가입, 로그인 성공/실패 얼러트 구현 ( 추후 모달 예정)

✨[PR]2025/02/17 중복 회원가입 검증 / 로그인 검증 - 김규남✨

---

funniture-fe/package-lock.json
funniture-fe/package.json
funniture-fe/src/App.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/user/Inquiry.js
funniture-fe/src/utils/tokenUtils.js

#52 
- 서버에서 받아온 토큰을 jwt_decode를 이용하여 복호화 하고, id 꺼내기 완료
- 로그인 ul는 변경 예정

✨[PR]2025/02/18 서버에서 받아온 토큰에서 id 꺼내기 - 김규남 ✨

---

funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/pages/admin/AdminMain.js
funniture-fe/src/pages/admin/AdminProduct.js
funniture-fe/src/pages/common/ListPage.js

#54 
판매 불가로 변경 또는 판매 가능으로 변경에 대한 작업 완료해뒀습니다.
원하는 상품들 체크 박스 체크 후 원하는 버튼 클릭하면 반영됩니다.
체크 내역 없이 버튼 클릭 시(나중에 모달로 msg 띄울 예정)
정상 반영

:sparkles: [PR] 2025/2/18 상품 상태 정보 변경 완료 [정예진] :sparkles:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/redux/modules/MemberModule.js

#52 
- 로그인 시, 서버에서 가져온 데이터 콘솔로 확인

🌐✨[PR]2025/02/18 로그인 한 유저의 대한 정보 가져오기 - 김규남✨🌐

---

funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/component/headerfooter.module.css
funniture-fe/src/pages/common/ListPage.js
funniture-fe/src/pages/common/Main.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/owner/OwnerProducts.js
funniture-fe/src/pages/owner/ownerProduct.module.css

💄 [PR] 2025/2/18 제공자 등록상품 css 페이지 완성 [정예진] 💄

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/redux/modules/MemberModule.js
funniture-fe/src/redux/modules/index.js
funniture-fe/src/utils/tokenUtils.js

#58 
- 서버에서 프론트로 데이터 불러오기
- reducer 만들어서 store에 저장
- 로직 수정

✨⚡️[PR]2025/02/18 서버에서 프론트로 데이터 불러오기 / 코드 수정-김규남⚡️✨

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/common/Main.js
funniture-fe/src/redux/modules/MemberModule.js

#63 
- 로그인한 회원 정보 받아오고, 새로고침 시 데이터가 초기값으로 변경되는 현상.

🎨🚚 로그인한 회원 정보 받아오고, 새로고침 시 데이터가 초기값으로 변경되는 현상 - 김규남 🎨🚚

---

funniture-fe/src/App.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/login/Login.js

#63 
- 로그인 시, 메인페이지로 이동하는데 데이터를 못 담고 있다가 새로고침 누르면 데이터가 표시됐었음
→ 로그인 시 데이터를 최상위 컴포넌트에 설정
- 어떤 페이지를 들어가든 로그인 한 회원 정보 사용 가능

🎨⚡️[PR]2025/02/19 로그인 시 최상위 컴포넌트에 정보 저장  - 김규남  🎨⚡️

---

funniture-fe/src/App.js
funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerProducts.js
funniture-fe/src/pages/owner/OwnerRegister.js
funniture-fe/src/pages/owner/ownerRegister.module.css

:lipstick: [PR] 2025/02/19 제공자 상품 등록 페이지 뼈대잡기 - 정예진 :lipstick:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/orders.module.css

#62
사용자 예약 주문 조회 & 개월수 필터링(백&프론트 연결)

:globe_with_meridians:[PR]2025/02/19 사용자 주문조회&개월수 필터링(백&프론트 연결) - 정은미:globe_with_meridians:

---

funniture-fe/.env
funniture-fe/package.json
funniture-fe/src/apis/.env
funniture-fe/src/apis/Apis.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/login/Singup.js

#77 
- 앞으로 서버 데이터가 필요할 때마다 fetch 구문을 작성(header , method)해야 했는데, 
- axios 로 설정 해놓음으로써 추후 효율적으로 서버의 데이터를 가져올 수 있음.

⚡️🚚[PR]2025/02/17 로그인 한 회원 정보 불러오기 axios로 수정 - 김규남🚚⚡️

---

funniture-fe/package-lock.json
funniture-fe/src/App.js
funniture-fe/src/apis/Apis.js
funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/admin/AdminProduct.js
funniture-fe/src/pages/common/ListPage.js
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/redux/modules/CategoryModuls.js

#83 
- axios 이용한 공용 api로  productAPI 수정
- 상품 상세페이지 페이지 연결 성정

:art: [PR] 2025/02/20 axios 이용한 공용 api로  productAPI 수정 - 정예진 :art:

---

funniture-fe/src/App.js
funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/OrdersReturn.js
funniture-fe/src/pages/user/mypage.css
funniture-fe/src/pages/user/orders.module.css

#88
- 사용자 마이페이지 탭 버튼 Link 연결 후 눌린 탭 css

:art:[PR]2025/02/20 사용자 마이페이지 탭 버튼 Link 연결 후 눌린 탭 css-정은미:lipstick:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/common/productDetail.module.css

:art: [PR] 2025/02/20 productDetail 조회 정보 추가 - 정예진 :art:

---

funniture-fe/src/apis/Apis.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/login/Singup.js
funniture-fe/src/pages/login/login.css
funniture-fe/src/pages/login/signup.css
funniture-fe/src/redux/modules/MemberModule.js

#87 
- 로그인 시, 비밀번호 8자 이상 돼야 로그인 버튼 활성화
- 회원 가입 시 이메일 @~. 입력해야 '인증번호 발송' 버튼 활성화
- 인증번호 6글자 입력해야 '인증하기' 버튼 활성화
- '비밀번호 입력' && ' 비밀번호 확인' 동일해야 '회원가입' 버튼 활성화

✨💄 [PR]2025/02/20 회원가입 / 로그인 검증 및 css 추가 - 김규남 💄✨

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/user/DetailOrder.js

:globe_with_meridians:[PR]2025/02/20 예약 상세페이지-백&프론트 연결-정은미:globe_with_meridians:

---

funniture-fe/src/pages/login/Login.js

#87
- 로그인 시 유효성 검증 추가했는데, 작업을 위해 주석 후 머지

🚑 [PR]2025/02/21 작업을 위해, 로그인 유효성 검증 주석하고 머지 -김규남🚑

---

funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/detailorder.module.css
funniture-fe/src/pages/user/mypage.css

:lipstick:[PR]2025/02/21 예약 상세페이지 CSS 수정-정은미:lipstick:

---

funniture-fe/src/component/Header.js

#97 
- 비회원도 마이페이지 버튼이 있어서 클릭 시 에러 발생 했으나, 로그인 한 회원만 마이페이지 버튼 보이게 설정
- 토큰의 권한 여부로 user / admin / owner 권한에 따라 각자 페이지로 이동

✨[PR]2025/02/21 로그인 한 회원만 마이페이지 버튼 보이게 설정 - 김규남✨

---

funniture-fe/src/App.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/login/FindPass.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/login/login.css

#96 
- 로그인 페이지에서 비밀번호 찾기(변경) 로직 구현

✨[PR]2025/02/21 로그인 페이지에서 비밀번호 변경 로직 완료 - 김규남✨

---

funniture-fe/src/App.js
funniture-fe/src/pages/user/RentalRegist.js
funniture-fe/src/pages/user/detailorder.module.css
funniture-fe/src/pages/user/rentalRegist.module.css

:lipstick:[PR]2025/02/21 예약 등록 페이지 CSS-정은미:lipstick:

---

funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/common/ListPage.js
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/common/productDetail.module.css
funniture-fe/src/pages/owner/OwnerProducts.js
funniture-fe/src/pages/owner/OwnerRegister.js
funniture-fe/src/pages/owner/ownerRegister.module.css

#85 #99
상품 등록 프론트, 백 및 cloudnary 연결하여 이미지 업로드

✨ [PR] 2025/02/21 상품 등록 + 이미지 cloudinary업로드 - 정예진 ✨

---

funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/user/RentalRegist.js

#103
- 상품상세페이지 -> 예약 등록페이지로 데이터 연결

:art:[PR]2025/02/21 상품상세페이지 데이터 예약 등록페이지로 연결 - 정은미:art:

---

funniture-fe/src/App.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/user/EditInfo.js
funniture-fe/src/pages/user/EditsInfo.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/UserConform.js
funniture-fe/src/pages/user/editInfo.css
funniture-fe/src/redux/modules/MemberModule.js

#98 
- EditsInfo , UserConfirm 컴포넌트 생성
- 마이페이지에서 개인 정보 변경 로직 구현 중
- 비밀번호 확인해야 변경 가능하게 구현 중

✨[PR]2025/02/21 마이페이지 개인 정보 변경 구현중 - 김규남 ✨

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/user/UserConform.js

#116 
- 사용자 마이 페이지에서 개인정보 수정 전, 비밀번호 재확인
- onKeyDown으로 엔티 시에도 동작

✨[PR]2025/02/23 사용자 마이페이지 비밀번호 인증 - 김규남 ✨

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/component/BtnModal.js
funniture-fe/src/pages/login/Login.js

#123 
- 로그인 실패 / 성공 시 모달창 적용
- 다른 부분은 추후에 적용 예정....

✨⚡️[PR]2025/02/23 로그인 실패 / 성공 시 모달창 적용 - 김규남 ⚡️✨

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/user/EditsInfo.js
funniture-fe/src/redux/modules/MemberModule.js

#126 
- 사용자 마이 페이지에서 기본 주소 불러왔음
- 기존 member Store에 address 정보 추가

✨[PR]2025/02/24 사용자 마이 페이지에서 주소 불러오기 - 김규남 ✨

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/user/EditsInfo.js

✨[PR]2025/02/24 사용자 마이페이지에서 주소 변경 완료 - 김규남 ✨

---

funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/component/BtnModal.js
funniture-fe/src/component/BtnModal.module.css
funniture-fe/src/component/headerfooter.module.css
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/common/productDetail.module.css
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/owner/OwnerRegister.js
funniture-fe/src/pages/owner/ownerProduct.module.css
funniture-fe/src/pages/user/EditsInfo.js
funniture-fe/src/redux/modules/index.js
funniture-fe/src/redux/modules/productReducer.js

#112 
#100 
#133 
상품 등록 및 예외처리 완료

✨ [PR] 2025/02/24 상품 등록 예외처리 및 완성 - 정예진✨

---

funniture-fe/src/App.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/user/EditsInfo.js
funniture-fe/src/pages/user/editsInfo.css
funniture-fe/src/redux/modules/MemberModule.js

#130 
- 사용자 마이페이지 회원 탈퇴
- 사용자 마이페이지 이미지 변경
- 사용자 마이페이지 비밀번호 변경
- 변경 완료 / 탈퇴 여부 등 전체 모달창 구현

✨[PR]2025/02/24 사용자 마이페이지 모든 기능 구현 - 규남 ✨

---

funniture-fe/src/apis/DeliveryAddressAPI.js
funniture-fe/src/pages/user/DeliveryAddressModal.js
funniture-fe/src/pages/user/RentalRegist.js
funniture-fe/src/pages/user/deliveryAddressModal.module.css

#142
- 예약등록페이지에서 배송지 변경 버튼 -> 모달창 배송지 전체 조회 - 백&프론트 연결

:sparkles:[PR]2025/02/25 배송지 전체 조회 - 백&프론트 연결-정은미:sparkles:

---

funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/login/login.css

#147 
- 로그인 유효성 검증 완료
→ 아이디  / 비밀번호 올바르게 입력해야 로그인 버튼 활성화
→ 아이디 / 비밀번호 하단에 small 빨간 텍스트 출력

✨[PR]2025/02/25 로그인 유효성 검증 (아이디 / 비밀번호) - 김규남✨

---

funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownermypage.module.css

:lipstick: [PR] 2025/02/25 제공자 메인에 상품 현황 출력하기 - 정예진 :lipstick:

---

funniture-fe/src/pages/login/FindPass.js
funniture-fe/src/pages/login/findPass.css
funniture-fe/src/pages/login/signup.css
funniture-fe/src/pages/owner/OwnerRegister.js

#153 
- 로그인 페이지에서 비밀번호 찾기 유효성 검증
→ 이메일 형식 / 비밀번호 형식 등

✨[PR]2025/02/25 로그인 페이지 비밀번호 찾기 유효성 검증 추가 - 김규남 ✨

---

funniture-fe/src/pages/user/DeliveryAddressModal.js
funniture-fe/src/pages/user/RentalRegist.js
funniture-fe/src/pages/user/deliveryAddressModal.module.css

#143
- 예약 등록페이지에서 배송지 변경버튼을 눌러 -> 배송지 선택 기능
- 완료 모달창

:sparkles:[PR]2025/02/25 배송지 선택&완료 모달창-정은미:sparkles:

---

funniture-fe/src/App.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/user/FavoritesPage.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/RecentProduct.module.css
funniture-fe/src/pages/user/Recentproduct.js
funniture-fe/src/pages/user/favoritesPage.module.css

#156 
#114 
관심상품 , 최근 본 상품 페이지 css 완료 및
최근 본 상품 상품 번호 localstorage에 저장까지 완료

✨ [PR] 2025/02/25 최근 본 상품 api에 넘길 준비 끝 - 정예진 ✨

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/user/RentalRegist.js

:globe_with_meridians:[PR]2025/02/25 예약 등록 백&프론트 연결 -정은미:globe_with_meridians:

---

funniture-fe/src/App.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/user/AppConvert.js
funniture-fe/src/pages/user/Convert.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/appConvert.css

#161 
- 사용자 → 제공자 전환 요청 페이지 구성 

💄[PR]2025/02/25 사용자의 제공자 전환 요청 페이지 구성 -김규남 💄

---

funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/layouts/AuthorityLayout.js
funniture-fe/src/pages/admin/AdminUser.js
funniture-fe/src/pages/user/AppConvert.js

#167 
- 관리자 페이지 생성 / 서버에서 필요한 데이터 불러옴

🌐 [PR]2025/02/26 관리자 페이지 생성 / 서버에서 필요한 데이터 불러옴  - 김규남 🌐

---

funniture-fe/src/App.js
funniture-fe/src/apis/ProductAPI.js
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/user/RecentProduct.module.css
funniture-fe/src/pages/user/Recentproduct.js

#169 
백 & 프론트 연결하여 DB에서 받은 데이터로 최근 본 상품 정보 뿌리기

:sparkles: [PR] 2025/02/26 최근 본 상품 완료 - 정예진 :sparkles:

---

funniture-fe/package-lock.json
funniture-fe/package.json
funniture-fe/src/pages/user/RentalRegist.js

#173
- 예약 완료 시 react-canvas-confetti 
- install 추가

:lipstick:[PR]2025/02/26 예약 완료 시 react-canvas-confetti -정은미:lipstick:

---

funniture-fe/src/App.js
funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/admin/AdminLeaver.js
funniture-fe/src/pages/admin/AdminOwner.js
funniture-fe/src/pages/admin/adminUser.module.css

#167 
- 관리자 페이지에서 사용자 및 제공자 데이터 불러오기

✨[PR]2025/02/26 관리자 페이지 사용자 / 제공자 데이터 불러오기 - 김규남✨

---

funniture-fe/src/apis/FavoriteAPI.js
funniture-fe/src/pages/common/ListPage.js
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/user/FavoritesPage.js
funniture-fe/src/pages/user/favoritesPage.module.css

✨ [PR] 2025/02/26 관심상품 조회 완성 - 정예진 ✨

---

funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/pages/admin/AdminConvert.js

🌐✨[PR]2025/02/27 제공자 전환 데이터 화면 출력 - 김규남✨🌐

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/ownerRental.module.css
funniture-fe/src/pages/user/Orders.js

#165
- 제공자 예약조회(탭별, 만료기간별 필터링) => 백&프론트 연결

:globe_with_meridians:[PR]2025/02/27 제공자 예약조회(탭별, 만료기간별 필터링) - 백&프론트 연결-정은미:globe_with_meridians:

---

funniture-fe/src/layouts/ownerlayout.css
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/ownerRental.module.css

#187
-  제공자 예약 조회 => 예약진행상태 select

:sparkles:[PR]2025/02/27 제공자 예약 조회 - 예약진행상태 select-정은미:sparkles:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/user/AppConvert.js

#182  
- 제공자 전환 신청 이후, 재 신청 대상자는 제출이 아닌 재신청으로 표시

✨[PR]2025/02/27 제공자 전환 신청 / 재신청 연결   - 김규남✨

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/component/Pagination.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/ownerRental.module.css

:sparkles:[PR]2025/02/27 제공자 예약조회 페이징 처리-정은미:sparkles:

---

funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/component/BtnModal.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/user/AppConvert.js
funniture-fe/src/redux/modules/MemberModule.js

#182 
- 제공자 전환 신청 이후 재 신청
-  관리자 페이지에 데이터 불러오기 
-  관리자 페이지, 전환신청 탭 클릭 시 모달창
-  제공자 신청 데이터 / 재신청 데이터 store에 저장 (member.owner)

✨[PR]2025/02/27 제공자 전환 신청 / 관리자 페이지 - 김규남 ✨

---

funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/admin/AdminLeaver.js
funniture-fe/src/pages/admin/AdminOwner.js
funniture-fe/src/pages/admin/AdminUser.js
funniture-fe/src/pages/login/FindPass.js

#199 
- 관리자 페이지에서 일반 사용자를 탈퇴 회원으로 전환
- 사용자 / 제공자 / 제공자 전환 / 탈퇴자 탭별로 색상 구분

💄✨[PR]2025/02/28 관리자 페이지 사용자를 탈퇴 회원으로 전환 / 버튼 css  - 김규남✨💄

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/component/Pagination.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/orders.module.css

#203
사용자별 주문 조회 페이징 처리 적용 (프론트&백 연결) 

:globe_with_meridians:[PR]2025/03/01 사용자별 주문 조회 페이징 처리 적용 (프론트&백 연결) - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/admin/Rental.js
funniture-fe/src/pages/admin/rental.module.css
funniture-fe/src/pages/owner/ownerRental.module.css

#204
- 관리자 예약정보 조회 페이징 처리 적용(프론트&백 연결)

:globe_with_meridians:[PR]2025/03/01 관리자 예약정보 조회 페이징 처리 적용(프론트&백 연결) - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/component/BtnModal.js
funniture-fe/src/pages/admin/AdminConvert.js

#208 
- 제공자 전환 신청자 반려 / 승인 로직
- 승인 시 제공자 탭으로 이동 / 반려 시 사용자 탭으로 이동

🌐✨[PR]2025/03/02 제공자 전환 신청 반려 / 승인 - 김규남✨🌐

---

funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/detailorder.module.css

#180
- 제공자별 주문 조회 (주문번호 클릭) -> 예약 상세정보 출력(모달, 주문 상세 컴포넌트 재사용)

:globe_with_meridians:[PR]2025/03/02 제공자 주문번호 클릭 시 예약 상세정보 출력 - 정은미:globe_with_meridians:

---

funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/detailorder.module.css

#211
- 주문 상세페이지에서 사용자와 제공자 각각 볼 수 있는 데이터를 구분하여 조건부로 표시하는 로직 구현

:globe_with_meridians:[PR]2025/03/02 주문 상세페이지 사용자, 제공자 각각 데이터 구분 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/user/AppConvert.js
funniture-fe/src/pages/user/SubmissionMessage.js
funniture-fe/src/pages/user/submissionMessage.module.css

#208 
제공자 전환 신청 후, 심사 텍스트 출력 및 기타 로직

🌐✨[PR]2025/03/02 제공자 전환 신청 후, 심사 텍스트 출력 및 기타 로직  -김규남 ✨🌐

---

funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/ownerRental.module.css

#214
- 전체&예약탭에서만 예약취소, 예약확정 버튼 보이게하기

:lipstick:[PR]2025/03/03 전체&예약탭에서만 예약취소, 예약확정 버튼 보이게하기 - 정은미:lipstick:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerRental.js

:globe_with_meridians:[PR]2025/03/03 다중선택하여 예약확정 백&프론트 연결 - 정은미:globe_with_meridians:

---

funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/ownerRental.module.css
funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/detailorder.module.css

#225
- 제공자 마이페이지 주문번호 클릭 -> 주문상세 구조 변경 CSS 

:lipstick:[PR]2025/03/03 제공자 마이페이지 주문번호 클릭 -> 주문상세 구조 변경 CSS - 정은미:lipstick:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/user/AppConvert.js
funniture-fe/src/pages/user/SubmissionMessage.js

#197 
-  제공자 전환 최초 신청 / 반려 메시지 확인 / 재 신청
-  관리자 승인 시, 제공자 페이지로 연결
-  관리자 반려 시, 반려 메시지 확인

🌐✨[PR]2025/03/03 제공자 전환 신청 / 반려 메시지 / 재신청 연결 - 김규남✨🌐

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/user/DetailOrder.js

#227
- 예약 대기 -> 예약 취소로 상태 백&프론트 연결

:sparkles:[PR]2025/03/03 예약 대기 -> 예약 취소로 상태 백&프론트 연결 - 정은미:sparkles:

---

funniture-fe/src/pages/owner/DeliverComModal.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/deliverComModal.module.css

#181
- 운송장, 택배사 더블클릭 -> 운송장 등록모달 CSS 

:lipstick:[PR]2025/03/03 운송장, 택배사 더블클릭 -> 운송장 등록모달 CSS - 정은미:lipstick:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/DeliverComModal.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/deliverComModal.module.css

#232
- 운송장 등록 백&프론트 연결
- 운송장 번호 또는 운송업체명이 null이고, rentalState가 '예약완료'일 경우만 
운송장 등록 모달 열기 가능하게 설정

:globe_with_meridians:[PR]2025/03/03 운송장 등록 백&프론트 연결:globe_with_meridians:

---

funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/admin/AdminLeaver.js
funniture-fe/src/pages/admin/AdminOwner.js
funniture-fe/src/pages/admin/AdminUser.js

#195 
#207 
- 관리자 페이지, 사용자 / 탈퇴자 전체 체크
- 데이터 클릭 시 상세 정보 출력
-  사용자 - 포인트 수정

✨[PR]2025/03/03 관리자 페이지 상세 정보 / 전체 체크 / 데이터 이동 - 김규남 ✨

---

funniture-fe/src/component/BtnModal.js

- 
- modal.body를 왼쪽 / 오른쪽 나눠놔서 예약 조회에서 출력 안 됨
- 모달 긴급 수정

[PR]2025/03/04 모달 바디 수정 - 김규남

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/RentalRegist.js

#238
- memberId 고정 값 -> 로그인 유저 값으로 변경

:globe_with_meridians:[PR]2025/03/04 memberId 고정 값 로그인 유저 값으로 변경 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/ChatAPI.js
funniture-fe/src/component/ChatModal.js
funniture-fe/src/pages/admin/AdminQnAPage.js
funniture-fe/src/pages/admin/AdminQnAPage.module.css

#223 
관리자 페이지의 질문 관리 페이지 백단과 연결 완료

:sparkles: [PR] 2025/03/04 관리자 페이지 질문 관리 백 & 프론트 연결 - 정예진 :sparkles:

---

funniture-fe/src/component/BtnModal.module.css

:lipstick:[PR]2025/03/04 모달 사이즈 제한하기 - 정은미:lipstick:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/user/AppConvert.js

#240 
- 제공자 전환 이미지 업로드 부분 수정
- 제공자 전환 유효성 검증 추가 (store_no 중복 여부 체크 / 필수갑 입력 안 할 시 제출 못함)

🐛✨[PR]2025/03/04  제공자 전환 유효성 검증 추가 - 김규남 ✨🐛

---

funniture-fe/src/apis/DeliveryAddressAPI.js
funniture-fe/src/pages/user/DeliveryAddress.js
funniture-fe/src/pages/user/RentalRegist.js

#121
- 신규배송지 등록 백&프론트 연결
- 주소찾기 API 사용

:globe_with_meridians:[PR]2025/03/04 신규배송지 등록 백&프론트 연결 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/DeliveryAddressAPI.js
funniture-fe/src/pages/user/DeliveryAddress.js
funniture-fe/src/pages/user/deliveryAddress.module.css

:globe_with_meridians:[PR]2025/03/04 배송지 수정 -> 백&프론트 연결 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/component/Header.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/admin/AdminLeaver.js
funniture-fe/src/pages/admin/AdminOwner.js
funniture-fe/src/pages/admin/AdminUser.js
funniture-fe/src/pages/login/Singup.js
funniture-fe/src/pages/user/Convert.js
funniture-fe/src/pages/user/SubmissionMessage.js
funniture-fe/src/pages/user/submissionMessage.module.css

#244 
#254 
- 관리자 페이지, 회원 리스트에 회원가입일 형식 변경 / 모달에도 적용
- 회원가입 / 로그아웃 / 정보 변경 / 관리자 페이지 등 전체 모달 적용

💄✨[PR]2025/03/04 회원가입일 형식 변경 /  전체 모달 적용 - 김규남 ✨💄

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/user/DeliveryAddress.js
funniture-fe/src/pages/user/OrdersReturn.js
funniture-fe/src/pages/user/deliveryAddress.module.css
funniture-fe/src/pages/user/ordersReturn.module.css

:globe_with_meridians:[PR]2025/03/05 사용상품/반납 조회 - 백&프론트 연결 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/admin/AdminLeaver.js
funniture-fe/src/pages/user/AppConvert.js

#262 
- 제공자 전환 신청 시, 유효성 검증 추가 
- 관리자 페이지 데이터 이동 시, 바로 렌더링 되게 수정

🐛[PR]2025/03/05 제공자 전환 신청 / 관리자 페이지 페이징 수정 - 김규남 🐛

---

funniture-fe/src/apis/ChatAPI.js
funniture-fe/src/component/ChatModal.js
funniture-fe/src/pages/admin/AdminManageChat.js

#268 
#223 
- 챗봇 진행시 관리자 연결 여부에 따른 관리자 연결하기 버튼 호출 및 진행과정에서의 이전질문보기 오류 수정
- 관리자 페이지의 질문관리에서 챗봇 질문 삭제 가능
(삭제 시 해당 질문과 하위의 모든 질문 삭제 가능)

✨ [PR] 2025/03/05 챗봇 진행 오류 수정 및 질문 삭제 가능 - 정예진 ✨

---

funniture-fe/src/component/ChatModal.js
funniture-fe/src/component/ChatModal.module.css
funniture-fe/src/pages/common/ProductDetailPage.js

:truck: [PR] 2025/03/05 페이지 연결용 -정예진 :truck:

---

funniture-fe/src/apis/PointAPI.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/mypage.css

:globe_with_meridians:[PR]2025/03/06 마이페이지 포인트 조회 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/mypage.css

#278
- 사용자 마이페이지 예약진행상태별 갯수 조회 백&프론트 연결

:globe_with_meridians:[PR]2025/03/06 사용자 마이페이지 예약진행상태별 갯수 조회 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/common/Inquiry.js
funniture-fe/src/pages/common/inquiryProduct.module.css

#277 
- 상품 등록 연결
-  상품 조회 연결 수정

✨[PR]2025/03/06 상품 문의 등록 연결  - 김규남 ✨

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/admin/Rental.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/orders.module.css

#281
- 사용자 마이페이지 (주문/배송) 날짜 선택 필터링 백&프론트 연결

:globe_with_meridians:[PR]2025/03/06 사용자 주문/배송 날짜 선택 필터링 - 정은미:globe_with_meridians:

---

funniture-fe/src/App.js
funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/common/Inquiry.js
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownerInquiry.module.css
funniture-fe/src/pages/owner/ownermypage.module.css

#283 
- 제공자 마이 페이지 문의 연결 / 스크롤 적용
- 상세페이지 문의 작성 수정 (로그인 한 회원만 문의 작성 보이게 / 필수값 모두 작성해야 등록 되게)

🌐✨[PR]2025/03/06 제공자 마이페이지 문의 연결 / 문의 작성 수정-  김규남✨🌐

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/user/DeliveryAddressModal.js
funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/RentalRegist.js
funniture-fe/src/pages/user/deliveryAddressModal.module.css
funniture-fe/src/pages/user/detailorder.module.css
funniture-fe/src/pages/user/orders.module.css
funniture-fe/src/pages/user/rentalRegist.module.css

#285
- 사용자 주문 상세페이지 선택 배송지로 수정하기 백&프론트 연결

:globe_with_meridians:[PR]2025/03/06 사용자 주문 상세페이지 선택 배송지로 수정하기 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownerInquiry.module.css
funniture-fe/src/pages/owner/ownerMainInquiry.module.css
funniture-fe/src/redux/modules/OwnerModule.js
funniture-fe/src/redux/modules/index.js

#283 
- 제공자 메인 페이지 문의 연결
- 제공자 페이지 '문의 사항'에 문의 연결
- ownerReducer에 문의 데이터 저장

🌐✨[PR]2025/03/06 제공자 메인 페이지 문의 연결 / 문의 페이지 문의 연결  -  김규남✨🌐

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownerInquiry.module.css
funniture-fe/src/redux/modules/OwnerModule.js

#293 
- 제공자 문의 페이지 페이징 처리
-  답변 여부에 따라 탭 구분

🌐✨[PR]2025/03/07 제공자 문의 페이지 페이징 처리 , 답변 여부에 따라 탭 구분 - 김규남✨🌐

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/user/OrderReturnRegist.js
funniture-fe/src/pages/user/OrdersReturn.js

:globe_with_meridians:[PR]2025/03/07 사용자 반납요청 백&프론트 연결-정은미:globe_with_meridians:

---

funniture-fe/src/App.js
funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/UserInquiry.js
funniture-fe/src/pages/user/mypageInquiry.module.css
funniture-fe/src/redux/modules/MemberModule.js

#298 
- 사용자 마이페이지 문의 데이터, 스토어에 저장
- 사용자 문의 마이페이지 css 틀 잡기

🌐✨[PR]2025/03/07 사용자 마이페이지 문의 데이터 스토어 저장  -  김규남 ✨🌐

---

funniture-fe/src/pages/owner/DeliveryInProgressModal.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/deliveryInProgressModal.module.css
funniture-fe/src/pages/user/OrderReturnRegist.js
funniture-fe/src/pages/user/OrdersReturn.js

#301
- 배송중 -> 배송완료 예약진행상태 수정(모달)

:globe_with_meridians:[PR]2025/03/07 배송중 -> 배송완료 예약진행상태 수정(모달) - 정은미:globe_with_meridians:

---

funniture-fe/src/pages/owner/DeliveryInProgressModal.js
funniture-fe/src/pages/owner/OwnerRental.js
funniture-fe/src/pages/owner/ownerRental.module.css
funniture-fe/src/pages/user/RentalRegist.js

#302
- 제공자 예약/배송/반납 페이지에서 배송중에서 배송완료로 예약진행상태 변경
&운송장번호, 운송업체 수정 (모달) 

:globe_with_meridians:[PR]2025/03/08 배송중에서 배송완료로 상태 변경&운송장 수정 - 정은미:globe_with_meridians:

---

funniture-fe/src/pages/owner/DeliveryInProgressModal.js
funniture-fe/src/pages/owner/OwnerRental.js

#304
- 예약 상태 변경(운송장 등록&반납요청->수거중, 수거중->반납완료)

:globe_with_meridians:[PR]2025/03/08 예약 상태 변경(운송장 등록&반납요청->수거중, 수거중->반납완료) - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/user/UserInquiry.js
funniture-fe/src/redux/modules/MemberModule.js

#306 
- 사용자 문의 페이지 , 문의 데이터 연결 
- css 및 페이징 처리

🌐✨[PR]2025/03/08  사용자 페이지 문의 조회 연결 및 css - 김규남 ✨🌐

---

funniture-fe/src/App.js
funniture-fe/src/apis/ReviewAPI.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/UserReview.js
funniture-fe/src/pages/user/mypagereview.module.css
funniture-fe/src/redux/modules/MemberModule.js

#308 
- 사용자 리뷰 페이지, 리뷰 불러오기
- 페이징 처리 및 css 
- 이미지 데이터 없을 경우, default값 적용

🌐✨[PR]2025/03/08 사용자 리뷰 페이지 조회 -김규남 ✨🌐

---

funniture-fe/src/apis/ReviewAPI.js
funniture-fe/src/pages/common/Inquiry.js
funniture-fe/src/pages/common/ProductDetailPage.js
funniture-fe/src/pages/common/Review.js
funniture-fe/src/pages/common/reviewProduct.module.css
funniture-fe/src/pages/user/UserInquiry.js

#310 
- 리뷰 데이터, 제품 상세페이지 연결 
-  및 css 

🌐✨[PR]2025/03/08 리뷰 데이터 제품 상세페이지 연결  -  김규남 ✨🌐

---

funniture-fe/src/App.js
funniture-fe/src/apis/NoticeAPI.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/admin/AdminLeaver.js
funniture-fe/src/pages/admin/AdminNotice.js
funniture-fe/src/pages/admin/AdminNotice.module.css
funniture-fe/src/pages/admin/AdminOwner.js
funniture-fe/src/pages/admin/AdminUser.js
funniture-fe/src/pages/admin/rental.module.css
funniture-fe/src/pages/common/Main.js
funniture-fe/src/pages/common/inquiryProduct.module.css
funniture-fe/src/pages/common/main.css
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/user/UserInquiry.js
funniture-fe/src/pages/user/mypageInquiry.module.css
funniture-fe/src/pages/user/mypagereview.module.css
funniture-fe/src/pages/user/ordersReturn.module.css
funniture-fe/src/pages/user/rentalRegist.module.css

:sparkles: [PR] 2024/03/09 공지사항 조회, 등록, 삭제 - 정예진 :sparkles:

---

funniture-fe/src/App.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/layouts/OwnerLayout.js
funniture-fe/src/layouts/ownerlayout.css
funniture-fe/src/pages/common/Main.js
funniture-fe/src/pages/common/Notice.js
funniture-fe/src/pages/owner/OwnerInfo.js
funniture-fe/src/pages/owner/OwnerInfo.module.css
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/OwnerNotice.js
funniture-fe/src/pages/owner/OwnerNoticeDetail.js
funniture-fe/src/pages/owner/ownerNotice.module.css
funniture-fe/src/pages/owner/ownermypage.module.css
funniture-fe/src/redux/modules/OwnerModule.js

#319 
- 업체 정보 조회 페이지 생성
-  업체정보 조회 백 프론트 연결
- 공지사항 텝 페이지 생성 및 연결
- 프론트 백 연결

:sparkles: [PR] 2025/03/09 제공자 업체정보 페이지 완성 - 정예진 :sparkles:

---

funniture-fe/src/App.js
funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/apis/ReviewAPI.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/OwnerReview.js
funniture-fe/src/pages/owner/ownerMainReview.module.css
funniture-fe/src/pages/owner/ownerReview.module.css
funniture-fe/src/pages/owner/ownermypage.module.css
funniture-fe/src/redux/modules/OwnerModule.js

#318 
- 제공자 메인 페이지 / 리뷰 페이지 연결 
- 제공자 메인페이지 css 적용했으나 잘 안 됨. 추후 고쳐볼 예정
- 페이징 처리 적용

🌐✨[PR]2025/03/09 제공자 메인 페이지 / 리뷰 페이지 연결 - 김규남✨🌐

---

funniture-fe/src/App.js
funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/admin/AdminSales.js
funniture-fe/src/pages/admin/adminSales.module.css

#322
- 월별 관리자 매출현황 조회 및 회사별 필터링 백&프론트 연결

:globe_with_meridians:[PR]2025/03/09 월별 관리자 매출현황 조회 및 회사별 필터링 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/ReviewAPI.js
funniture-fe/src/pages/user/UserInquiry.js
funniture-fe/src/pages/user/UserReview.js
funniture-fe/src/pages/user/mypagereview.module.css
funniture-fe/src/redux/modules/MemberModule.js

#324 
- 사용자 마이페이지 작성한 리뷰 , 작성 가능 리뷰 / 페이지 네이션

💄🌐✨[PR]2025/03/09 사용자 마이페이지 작성한 리뷰 , 작성 가능 리뷰 / 페이지 네이션 - 김규남✨ 🌐💄

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/apis/ReviewAPI.js
funniture-fe/src/pages/common/Main.js
funniture-fe/src/pages/common/main.css
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/redux/modules/MemberModule.js
funniture-fe/src/redux/modules/OwnerModule.js

#326 
- 메인페이지 리뷰 데이터 출력 (일단 리뷰 달린 최신 순으로 출력)
- 제공자 페이지 문의 및 리뷰 데이터 없을 때 나는 에러 수정

🌐✨[PR]2025/03/09 메인페이지 리뷰 데이터 출력 - 김규남✨🌐

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/apis/ReviewAPI.js
funniture-fe/src/pages/user/UserReview.js
funniture-fe/src/pages/user/mypagereview.module.css

#297 
- 사용자 페이지 리뷰 등록
-  리뷰 등록 시, 작성한 리뷰 탭으로 이동
- 리뷰 등록 시, 완료 모달
- 리뷰내용 적지 않고 등록 시, 오류 모달

🌐✨[PR]2025/03/10 사용자 페이지 리뷰 등록 - 김규남 ✨🌐

---

funniture-fe/src/pages/admin/Rental.js

#332
- 관리자 예약정보 단일 드롭다운 형식으로 수정

:art:[PR]2025/03/10 관리자 예약정보 단일 드롭다운 형식으로 수정 - 정은미:art:

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/owner/ownerInquiry.module.css

#331 
- 문의 답변 / 유효성 검사 / 바로 렌더링은 안 됨!

🌐✨[PR]2025/03/10  문의 답변 / 유효성 검사  - 김규남 ✨🌐

---

funniture-fe/src/pages/admin/AdminSales.js
funniture-fe/src/pages/owner/OwnerSales.js
funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/RentalRegist.js

:art:[PR]2025/03/10 렌탈 시 할인율 전체 적용 -정은미:art:

---

funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/pages/admin/AdminProduct.js
funniture-fe/src/pages/admin/adminSales.module.css
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownerInquiry.module.css
funniture-fe/src/pages/owner/ownerReview.module.css
funniture-fe/src/pages/owner/ownermypage.module.css
funniture-fe/src/pages/user/orders.module.css

#340 
- 로그인 과 동시에 접속자 수 증가 연결,
- css수정본들 체크

✨ [PR] 2025/03/10 접속자 수 반영 및 조회 - 정예진 ✨

---

funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/Orders.js

:art:[PR]2025/03/11 사용자 주문 금액 수정 - 정은미:art:

---

funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownerInquiry.module.css
funniture-fe/src/pages/owner/ownerNotice.module.css
funniture-fe/src/pages/owner/ownermypage.module.css

:lipstick: [PR] 2025/03/11 제공자 main css 변경 - 정예진 :lipstick:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerMyPage.js

#344 
- 제공자 마이페이지 메인 예약현황 카운트 백&프론트 연결

:sparkles:[PR]2025/03/11 제공자 마이페이지 메인 예약현황 카운트 - 정은미:sparkles:

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/user/UserInquiry.js
funniture-fe/src/pages/user/mypageInquiry.module.css

#346 
- 제공자 문의 답변에 따른 사용자 페이지 연결 

🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 사용자 페이지 연결  -  김규남 ✨🌐

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/OrdersReturn.js

:globe_with_meridians:[PR]2025/03/11 계약만료 갯수 카운트 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownermypage.module.css

#351
- 제공자 이번 달 매출 차트 백&프론트 연결

:globe_with_meridians:[PR]2025/03/11 제공자 이번 달 매출 차트 - 정은미:globe_with_meridians:

---

funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/pages/common/Inquiry.js
funniture-fe/src/pages/common/inquiryProduct.module.css
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/ownermypage.module.css
funniture-fe/src/pages/user/UserInquiry.js
funniture-fe/src/pages/user/UserReview.js
funniture-fe/src/redux/modules/MemberModule.js
funniture-fe/src/redux/modules/OwnerModule.js

#353 
- 제공자 문의 답변에 따른 상세페이지 연결 , 기타 css
-  제공자 문의 답변에 따른 사용자 페이지 연결

🌐✨[PR]2025/03/11 제공자 문의 답변에 따른 상세페이지 연결  - 김규남✨ 🌐

---

funniture-fe/src/pages/admin/AdminMain.js
funniture-fe/src/pages/admin/adminMain.module.css

:sparkles: [PR] 2025/03/11 관리자 그래프 작업중 - 정예진 :sparkles:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/admin/AdminMain.js
funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/detailorder.module.css
funniture-fe/src/pages/user/orders.module.css

#357
관리자 매출현황 차트(월별,일별) 백&프론트 연결

:sparkles:[PR]2025/03/12 관리자 매출현황 차트(월별,일별) - 정은미:sparkles:

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/admin/AdminMain.js

:globe_with_meridians: [PR]2025/03/12 관리자 메인 이번 달 매출 업체 TOP5 - 정은미:globe_with_meridians:

---

funniture-fe/src/pages/user/DetailOrder.js
funniture-fe/src/pages/user/detailorder.module.css
funniture-fe/src/pages/user/orders.module.css

:art:[PR]2025/03/12 사용자 상세페이지 예약취소 수정 - 정은미:art:

---

funniture-fe/src/pages/user/UserReview.js

📝[PR]2025/03/12 문의 삭제 수정 등 - 김규남📝

---

funniture-fe/src/pages/user/DeliveryAddress.js
funniture-fe/src/pages/user/DeliveryAddressModal.js
funniture-fe/src/pages/user/MyPage.js

- 사용자 배송지관리 삭제&신규배송지 등록(모달)&사용자 마이페이지 진행상태 카운트 수정

:bug:[PR]2025/03/12 사용자 배송지관리 삭제&신규배송지 등록(모달)&사용자 마이페이지 진행상태 카운트 수정 - 정은미:bug:

---

funniture-fe/src/pages/admin/adminProduct.module.css
funniture-fe/src/pages/admin/adminSales.module.css
funniture-fe/src/pages/admin/rental.module.css
funniture-fe/src/pages/owner/OwnerSales.js

:lipstick:[PR]2025/03/12 관리자 테두리 굵기 통합 - 정은미:lipstick:

---

funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/user/UserReview.js

💄[PR]2025/03/13 리뷰 작성 입력 안 되던 거 수정  - 김규남 💄

---

funniture-fe/src/apis/RentalAPI.js
funniture-fe/src/pages/admin/AdminMain.js
funniture-fe/src/pages/user/MyPage.js
funniture-fe/src/pages/user/Orders.js
funniture-fe/src/pages/user/OrdersReturn.js
funniture-fe/src/pages/user/RentalRegist.js

:art:[PR]2025/03/13 확인용 구문 제거 - 정은미:art:

---

funniture-fe/src/App.js
funniture-fe/src/apis/AdminAPI.js
funniture-fe/src/apis/Apis.js
funniture-fe/src/apis/InquiryAPI.js
funniture-fe/src/apis/MemberAPI.js
funniture-fe/src/apis/ReviewAPI.js
funniture-fe/src/pages/admin/AdminConvert.js
funniture-fe/src/pages/admin/AdminLeaver.js
funniture-fe/src/pages/admin/AdminOwner.js
funniture-fe/src/pages/admin/AdminUser.js
funniture-fe/src/pages/common/Inquiry.js
funniture-fe/src/pages/login/Login.js
funniture-fe/src/pages/owner/OwnerInquiry.js
funniture-fe/src/pages/owner/OwnerMyPage.js
funniture-fe/src/pages/owner/OwnerReview.js
funniture-fe/src/pages/user/AppConvert.js
funniture-fe/src/pages/user/Convert.js
funniture-fe/src/pages/user/EditsInfo.js
funniture-fe/src/pages/user/UserConform.js
funniture-fe/src/pages/user/UserInquiry.js
funniture-fe/src/pages/user/UserReview.js

📝[PR]2025/03/13 console 구문 삭제 , 주석 삭제 -김규남 📝

---

funniture-fe/src/pages/owner/OwnerSales.js

제공자 정산 회원명 수정
